jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          # 安装编译全部依赖，重点 mingw-w64-x86_64-pcre
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-pcre
            mingw-w64-x86_64-pthreads
            mingw-w64-x86_64-gdi
            mingw-w64-x86_64-winsock

      - name: Build inside MSYS2 MINGW64
        shell: msys2 {0}
        run: |
          mingw32-make clean
          mingw32-make
